version: "3.9"

services:

  mongodb:
    image: mongo:8.0
    container_name: mongodb-NovaTech
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  tienda-online:
    build: .
    container_name: NovaTech-api
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/NovaTech

volumes:
  mongodb_data: